name: Feature request
description: Propose a new feature or enhancement
title: "[FEATURE] <short description>"
labels: enhancement
body:
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this needed?
  - type: textarea
    id: implementation
    attributes:
      label: Proposed implementation
      description: How could this be done?